# Generated by Django 3.2.25 on 2024-06-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0003_alter_cart_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='littlelemonAPI.menuitem'),
        ),
    ]
